config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'braintree/new'
  post 'braintree/checkout'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root 'static#home'
  # if you are using Clearance gem, $ all clearance:routes
  #it will generate signin, signup and logout path in session controller
  # also generate password path.
  # redirect to homepage
  resources :listings do
    resources :bookings, only: [:create, :new, :show]
  end

  resources :tags
get "/auth/:provider/callback" =>"sessions#create_form_omniauth"


  # callback URL, URL that redirects the user from Facebook to your app
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   belongs_to :user
       def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user #listing table is belong_to user
  has_many :tags, through: :listing_tags, dependent: :destroy
  has_many :listing_tags, :dependent => :destroy
  has_many :bookings 
  # one user can have many tags, listing_tag is the middle table to connect both table.
  # destroy is when user delete certain tags, it will be deleted entirely.


end

app/models/listing_tag.rb
class ListingTag < ApplicationRecord
end

app/models/seed.rb
user = {}
user['password'] = 'asdf'
user['password_confirmation'] = 'asdf'

ActiveRecord::Base.transaction do
  20.times do
    user['first_name'] = Faker::Name.first_name
    user['last_name'] = Faker::Name.last_name
    user['gender'] = rand(1..2)
    user['nationality'] = Faker::Address.country
    user['email'] = Faker::Internet.email

    user['phone'] = Faker::PhoneNumber.phone_number
    user['country'] = Faker::Address.country
    user['birthdate'] = Faker::Date.between(50.years.ago, Date.today)

    User.create(user)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_many :bookings #user can have many booking
#In app/models/user.rb    has_many :authentications, :dependent => :destroy
# create_with_auth_hash will create a User object based on the information given by the provider
# This setup is meant for the user to key in his/her own Facebook password to log in to our app and such that we need not store this user’s password
  def self.create_with_auth_and_hash(authentication, auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
    #  user = User.create!(first_name: auth_hash["info"]["name"], email: auth_hash["extra"]["raw_info"]["email"])
      u.authentications << (authentication)
      u.password = SecureRandom.hex(7)
   end
    #  auto generate password when you signin with facebook.
    # return user
  end

  def fb_token
   x = self.authentications.where(:provider => :facebook).first
   return x.token unless x.nil?
  end
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController

  def show
  end

  def new
    @client_token = Braintree::ClientToken.generate
  end

  def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => "10.00", #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
end

app/controllers/user_controller.rb
class UsersController < Clearance::UsersController
    # 
    # def show
    #     @user = User.find(params[:id])
    # end
    #
    # def create
    #     @user = user_from_params
    #
    #     if @user.save
    #       sign_in @user
    #       redirect_back_or url_after_create
    #     else
    #       render template: "users/new"
    #     end
    # end
    #
    # private
    # def user_params
    #     params.require(:user).permit(:full_name, :email, :password, :gender, :age, :avatar)
    # end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listing_tags_helper.rb
module ListingTagsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/index.html.erb
<h1>Braintree#index</h1>

<%= link_to "Make Payment", braintree_new_path %>
<p>Find me in app/views/braintree/index.html.erb</p>

app/views/braintree/new.html.erb
<h1>Braintree#new</h1>
<p>Find me in app/views/braintree/new.html.erb</p>

<%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

  <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
  <div id="card-number" class="hosted-field"></div>

  <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
  <div id="expiration-date" class="hosted-field"></div>

  <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
  <div id="cvv" class="hosted-field"></div>

  <%= form.hidden_field "payment_method_nonce" %>

  <div class="submit-payment-btn">
    <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
  </div>
<% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


<script>
  var submit = document.querySelector("#submit-payment-btn");
  var form = document.querySelector('#cardForm');

  braintree.client.create({
    // Replace this with your own authorization.
    authorization: '<%= @client_token %>'
  }, function (clientErr, clientInstance) {
    if (clientErr) {
      // Handle error in client creation
      return;
    }

    braintree.hostedFields.create({
      client: clientInstance,
      styles: {
        'input': {
          'font-size': '14pt'
        },
        'input.invalid': {
          'color': 'red'
        },
        'input.valid': {
          'color': 'green'
        }
      },
      fields: {
        number: {
          selector: '#card-number',
          placeholder: '4111 1111 1111 1111'
        },
        cvv: {
          selector: '#cvv',
          placeholder: '123'
        },
        expirationDate: {
          selector: '#expiration-date',
          placeholder: '10/2019'
        }
      }
    }, function (hostedFieldsErr, hostedFieldsInstance) {
      if (hostedFieldsErr) {
        // Handle error in Hosted Fields creation
        return;
      }

      submit.removeAttribute('disabled');

      form.addEventListener('submit', function (event) {
        event.preventDefault();

        hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
          if (tokenizeErr) {
            // Handle error in Hosted Fields tokenization
            return;
          }

          // Put `payload.nonce` into the `payment_method_nonce` input, and then
          // submit the form. Alternatively, you could send the nonce to your server
          // with AJAX.
          document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
          form.submit();
        });
      }, false);
    });
  });



</script>