config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'braintree/new'
  post 'braintree/checkout'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  root 'static#home'
  # if you are using Clearance gem, $ all clearance:routes
  #it will generate signin, signup and logout path in session controller
  # also generate password path.
  # redirect to homepage
  resources :listings do
    resources :bookings, only: [:create, :new, :show]
  end

  resources :tags
get "/auth/:provider/callback" =>"sessions#create_form_omniauth"


  # callback URL, URL that redirects the user from Facebook to your app
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
   belongs_to :user
       def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user #listing table is belong_to user
  has_many :tags, through: :listing_tags, dependent: :destroy
  has_many :listing_tags, :dependent => :destroy
  has_many :bookings 
  # one user can have many tags, listing_tag is the middle table to connect both table.
  # destroy is when user delete certain tags, it will be deleted entirely.


end

app/models/listing_tag.rb
class ListingTag < ApplicationRecord
end

app/models/seed.rb
user = {}
user['password'] = 'asdf'
user['password_confirmation'] = 'asdf'

ActiveRecord::Base.transaction do
  20.times do
    user['first_name'] = Faker::Name.first_name
    user['last_name'] = Faker::Name.last_name
    user['gender'] = rand(1..2)
    user['nationality'] = Faker::Address.country
    user['email'] = Faker::Internet.email

    user['phone'] = Faker::PhoneNumber.phone_number
    user['country'] = Faker::Address.country
    user['birthdate'] = Faker::Date.between(50.years.ago, Date.today)

    User.create(user)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :authentications, :dependent => :destroy
  has_many :listings
  has_many :bookings #user can have many booking
#In app/models/user.rb    has_many :authentications, :dependent => :destroy
# create_with_auth_hash will create a User object based on the information given by the provider
# This setup is meant for the user to key in his/her own Facebook password to log in to our app and such that we need not store this user’s password
  def self.create_with_auth_and_hash(authentication, auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
    #  user = User.create!(first_name: auth_hash["info"]["name"], email: auth_hash["extra"]["raw_info"]["email"])
      u.authentications << (authentication)
      u.password = SecureRandom.hex(7)
   end
    #  auto generate password when you signin with facebook.
    # return user
  end

  def fb_token
   x = self.authentications.where(:provider => :facebook).first
   return x.token unless x.nil?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @listing = Listing.find(params[:listing_id])
    @booking = current_user.bookings.new(booking_params)
    # @booking = new_booking (user can have many booking)
    @booking.listing = @listing
    # one listing can only available for one booking.
    if @booking.save
      # redirect to booking#show
      flash[:success] = "Welcome to my house...."
      redirect_to listing_booking_path(@listing, @booking)
    else
      flash[:danger] = "Booking failed!"
    end
  end

  def destroy
  end

  def show
    @listing = Listing.find(params[:listing_id])
    @booking = Booking.find(params[:id])
  end

  def booking_params
      params.require(:booking).permit(:number_guests, :start_date, :end_date)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    @listing = listing.all
  end

  def new
    @listing = Listing.new
    # Listing.new (calling method from model Listing)
    # passing the command to @listing.
  end

  def create
    @listing = current_user.listings.new(listing_params)
    # @lising is
    if @listing.save
      # redirect_to @listing
      redirect_to listing_path(@listing)
      # redirect_to "listings/#{@listing.id}"
    else
      redirect_to listing_path
    end
  end


  def show
    @listing = Listing.find(params[:id])
    @booking = @listing.bookings.new
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      flash[:success] = "listed updated!"
    else
      flash[:danger] = "Somethings wrong?"
    end
  end


  def find_listing
    @listing = listing.find(param[:id])

  end

  private
  # that activate params
  def listing_params
      params.require(:listing).permit(:title, :description, :property_type, :room_type, :guest, :bedroom, :bethroom, :price, :address)
      # what is this line ?
      # 'permit' allow the items above to show as per schema. Anything other than that will not be shown.
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
end

app/controllers/user_controller.rb
class UsersController < Clearance::UsersController
    # 
    # def show
    #     @user = User.find(params[:id])
    # end
    #
    # def create
    #     @user = user_from_params
    #
    #     if @user.save
    #       sign_in @user
    #       redirect_back_or url_after_create
    #     else
    #       render template: "users/new"
    #     end
    # end
    #
    # private
    # def user_params
    #     params.require(:user).permit(:full_name, :email, :password, :gender, :age, :avatar)
    # end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listing_tags_helper.rb
module ListingTagsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/form.html.erb
<%= f.hidden_field :listing_id, value: @listing.id %>
<!--#what is this line for?  -->

<%= form_for [@listing,  @booking] , do |f| %>
  <div class="num_guests">
    <%= f.label :num_guests %>
    <%= f.text_field :email, type: 'email' %>
  </div>

  <div class="start_date">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="end_date">
    <%= f.label :end_date %>
    <%= f.date_field :end_date %>
  </div>

  <div class="max_guests">
    <%= f.label :max_guests %>
    <%= f.number_feild :max_guests %>
  </div>

  <%= f.submit "Submit Booking" %>
  <% end %>

app/views/bookings/show.html.erb
<h1>Thank you! We're looking forward to host you! xoxo </h1>

<p>Reservations#show</p>
<p>Find me in app/views/reservations/show.html.erb</p>


Congratulation! You can now visit <%= @listing.title %> and stay there from <%= @booking.start_date %> to <%= @booking.end_date %>.

app/views/listings/index.html.erb
<h1>Title: <%= @listing.title</h1>


<p> Description <%= @listing.description %></p>
<p> Max Guest <%= @listing.max_guests %></p>
<p> Price: <% @listing.price %></p>
<%= link_to "Edit", edit_listing_path (@listing) %>
<%= render "bookings/form"%> <!-- #direct to booking/form--!>

app/views/listings/new.html.erb
<!-- <div id="listing" class="new-listing"> -->
  <%# form_for @listing do |form| %>
    <%# render partial: '/listings/form', object: form %>
  <%# end %>
<!-- </div> --> 
<%= form_for @listing do |form| %>
<div class="container">
  <div class="row">
    <div class="col-md-3 left">
    </div>

      <div class="col-md-6 center">

        <h1>CREATE YOUR LISTING</h1>

        <div class="title-field">
          <%= form.label :title %>
          <%= form.text_field :title %>
        </div>

        <!-- <div class="avatar-field">
          <%= form.label :upload%>
          <%= form.file_field :avatars, multiple: true %>
        </div> -->

        <div class="description-field">
          <%= form.label :description %>
          <%= form.text_field :description %>
        </div>


        <div class="property-type-field">
           <%= form.label :property_type %>
           <%= form.select :property_type, options_for_select([["guesthouse", :guesthouse], ["hotel", :hotel], ["apartment", :apartment], ["townhouse", :townhouse], ["cabin", :cabin], ["house", :house], ["bungalow", :bungalow]])%>
        </div>

        <div class="room-type-field">
          <%= form.label :bedroom %>
          <%= form.number_field :bedroom, min: 1, max: 50, step: 1 %>
        </div>

        <div class="guest-field">
          <%= form.label :guest %>
          <%= form.number_field :guest, min: 1, max: 12, step: 1 %>
        </div>

        <div class="bedroom-field">
          <%= form.label :bedroom %>
          <%= form.number_field :bedroom, min: 1, max: 12, step: 1 %>
        </div>

        <div class="bathroom-field">
          <%= form.label :bathroom %>
          <%= form.number_field :bathroom, min: 1, max: 12, step: 1 %>
        </div>

        <div class="price-field">
          <%= form.label :price %>
          <%= form.number_field :price, min: 1, step: 1 %>
        </div>

        <div class="address-field">
          <%= form.label :address %>
          <%= form.text_field :address %>
        </div>

        <div class="form-group">
          <%= form.label :tags,  "Amenities:" %>
          <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :tag_content %>
        </div>

        <div class="submit-field">
          <%= form.submit %>
        </div>


       </div>

       <div class="col-md-3 right">
       </div>

    </div>
  </div>
</div>
<% end %>

app/views/listings/show.html.erb
<p>THIS IS LISTING SHOW</p>

<h1> Title: <%= @listing.title %></h1>
<p> Description: <%= @listing.description %> </p>
<p> property_type: <%= @listing.property_type %> </p>
<p> Room Type: <%= @listing.room_type %> </p>
<p> Guest: <%= @listing.guest %> </p>
<p> Bedroom: <%= @listing.bedroom %> </p>
<p> Bathroom: <%= @listing.bathroom %> </p>
<p> Price: <%= @listing.price %> </p>
<p> Address: <%= @listing.address %> </p>

<%= form_for [@listing, @booking] do |f| %> #form_for is an element if i would like to have @listing and @booking's elememnt be ruby code. 
<div class="start_date">
  <%= f.label :start_date %>
  <%= f.date_field :start_date %>
</div>

<div class="end_date">
  <%= f.label :end_date %>
  <%= f.date_field :end_date %>
</div>

<button type="submit">Confirm Booking</button>

<% end %>
</form>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/index.html.erb
<table>
  <% @user.each do |user| %>
    <tr>
      <td><%= link_to user.email, user %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>